# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# source 'https://git.coding.net/hging/Specs.git'

target 'testRnProjectWork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testRnProjectWork

  # target 'testRnProjectWorkTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  platform :ios, '8.0'

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

end
